INSERT INTO BANK(NAME) VALUES('bank1');
INSERT INTO BANK(NAME) VALUES('bank2');


INSERT INTO BANKER (MAIL, PASSWORD, FIRSTNAME, LASTNAME, REGISTRATED,BANK_ID) VALUES('1','1','1','1','1',1);
INSERT INTO BANKER (MAIL, PASSWORD, FIRSTNAME, LASTNAME, REGISTRATED,BANK_ID) VALUES('2','2','1','1','1',1);

INSERT INTO CLIENT (MAIL, PASSWORD, FIRSTNAME, LASTNAME, REGISTRATED) VALUES('3','3','1','1','1');
INSERT INTO CLIENT (MAIL, PASSWORD, FIRSTNAME, LASTNAME, REGISTRATED) VALUES('4','4','1','1','1');
INSERT INTO CLIENT (MAIL, PASSWORD, FIRSTNAME, LASTNAME, REGISTRATED) VALUES('5','5','1','1','1');
INSERT INTO CLIENT (MAIL, PASSWORD, FIRSTNAME, LASTNAME, REGISTRATED) VALUES('6','6','1','1','1');

INSERT INTO BILL(BILL_NUMBER,CLIENT_ID) VALUES('123',1);
INSERT INTO BILL(BILL_NUMBER,CLIENT_ID) VALUES('124',1);
INSERT INTO BILL(BILL_NUMBER,CLIENT_ID) VALUES('125',1);
INSERT INTO BILL(BILL_NUMBER,CLIENT_ID) VALUES('126',2);
INSERT INTO BILL(BILL_NUMBER,CLIENT_ID) VALUES('127',2);

INSERT INTO BANK_BANKERS(BANK_ID,BANKER_ID) VALUES(1,1);
INSERT INTO BANK_BANKERS(BANK_ID,BANKER_ID) VALUES(1,2);

INSERT INTO BANK_BILLS(BANK_ID,BILL_ID) VALUES(1,1);
INSERT INTO BANK_BILLS(BANK_ID,BILL_ID) VALUES(1,2);